### ISSUE TITLE
Square Brackets in titles

### ISSUE THREAD

**Issue by Kolophonium0** [zpd-digital-editions/Diskmags#4]
In mediawiki theres no square brackets in titles allowed. For this we need something else

**Comment by TomashWue** [comment]
I will fix it using regexp. Round brackets?

**Comment by Kolophonium0** [comment]
Openrefine might be safer. Round brackets are good. But we might need to check if (German) for example is a needed difference.

**Comment by TomashWue** [comment]
I would keep the content between brackets. Otherwise, we lose the references to our source data.

**Comment by torstenroeder** [comment]
Square brackets are currently used for what? Are they part of the original titles? Or do these come from the databases? For reference to source data, it would be better to rely on stable urls.

**Comment by TomashWue** [comment]
They were the part of original titles. Now, all square brackets are replaced by round ones. But they are well linked
