### ISSUE TITLE
Spelling of the project/repo name

### ISSUE THREAD

**Issue by rettinghaus** [zpd-digital-editions/Diskmags#6]
There are different spellings all over. Is the correct one "Diskmag Project" or "DiskMag Project"? Also _diskmags_ sometimes is capitalized. It would be good to unify spellings as far as possible.

**Comment by torstenroeder** [comment]
Thanks. Correct spellings are: "diskmags" for disk magazines (technical term), "Diskmag Catalog" for the project (proper name). No camel case.
